name: movies_db
description: A new Flutter project to learn how network works

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  page_view_indicators: ^2.0.0
  smooth_page_indicator: any
  lottie: any
  auto_size_text: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Extralight.ttf
          weight: 200
        - asset: assets/fonts/urbanist/Urbanist-Thin.ttf